//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVeXeKhach
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeXe
    {
        public int MaVX { get; set; }
        public string TenKH { get; set; }
        public string SDTKH { get; set; }
        public int MaCX { get; set; }
        public string MaNV { get; set; }
    
        public virtual ChuyenXe ChuyenXe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
